name       : ruby-builder
version    : 3.2.4
release    : 4
source     :
    - https://rubygems.org/downloads/builder-3.2.4.gem : 99caf08af60c8d7f3a6b004029c4c3c0bdaebced6c949165fe98f1db27fbbc10
license    : MIT
component  : programming.ruby
summary    : RubyGem - builder
description: |
    Builder provides a number of builder objects that make creating structured data simple to do. Currently the following builder objects are supported: * XML Markup * XML EventsBuilder provides a number of builder objects that make creating structured data simple to do. Currently the following builder objects are supported: XML Markup and XML Events.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
